Vagrant.require_version ">= 1.6.3"

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "wesovi-acceptance-tests-ng-host"
DOCKER_HOST_VAGRANTFILE = "./DockerHostVagrantfile"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  
  config.vm.define "postgresql" do |database|
    database.vm.provider "docker" do |docker|
      docker.build_dir = "./containers/postgresql"
      docker.build_args = ["-t=wesovi/postgresql","--rm=true"]
      docker.name  = "postgresql"
      docker.ports = %w(5432:5432)
      docker.vagrant_machine = "#{DOCKER_HOST_NAME}"
      docker.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
    end
  end
  
  config.vm.define "micro-service-extraction" do |extraction|
    extraction.vm.provider "docker" do |docker|
      docker.build_dir = "./containers/micro-service-extraction"
      docker.build_args = ["-t=wesovi/micro-service-extraction","--rm=true"]
      docker.name  = "micro-service-extraction"
      docker.ports = %w(8081:8081)
      docker.remains_running = true
      docker.vagrant_machine = "#{DOCKER_HOST_NAME}"
      docker.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
    end
  end
  
  config.vm.define "micro-service-insertion" do |insertion|
    insertion.vm.provider "docker" do |docker|
      docker.build_dir = "./containers/micro-service-insertion"
      docker.build_args = ["-t=wesovi/micro-service-insertion","--rm=true"]
      docker.name  = "micro-service-insertion"
      docker.ports = %w(8082:8082)
      docker.vagrant_machine = "#{DOCKER_HOST_NAME}"
      docker.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
    end
  end

end