Vagrant.require_version ">= 1.6.3"

VAGRANTFILE_API_VERSION = "2"
#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "wesovi-acceptance-tests-ng-host"
DOCKER_HOST_VAGRANTFILE = "./DockerHostVagrantfile"




Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  	config.vm.define "wesovi-acceptance-tests-ng-host"
  	config.vm.box = "ubuntu/trusty64"
  	config.vm.network "private_network", ip: "192.168.50.4"
  	config.vm.synced_folder "./containers", "/opt/containers"
  	
  	config.vm.provision "shell", path: "script.sh"
	config.ssh.forward_agent = true
	
	config.vm.provider "virtualbox" do |v|
	    v.name = "Wesovi QA Environment"
	    v.customize ["modifyvm", :id, "--memory", "2048"]
	end
	
end